### ISSUE TITLE
Separate calculations into each class

### ISSUE THREAD

**Issue by Quesys-tech** [MPS-Basic/MPS-Basic#10]
高精度手法を見据えて計算を分割してモジュール化する
- MPSクラスはPressureCalculationInterfaceクラスのインスタンスをメンバーにもつ。
    - PressureCalculationInterfaceクラスはインターフェースとして使い具体的な実装は持たせない
    - PressureCalculationInterfaceクラスを継承してEMPSPressureクラスを書き、陽解法を実装する
    - Poisson方程式を使う場合にはImplicitCalculatorクラスを書く
        - 自由表面判定はFreesurfaceDetectionInterfaceクラスをインターフェースとして使う
- ひし形継承を防ぐためにインターフェース以外の継承を禁止する

**Comment by iori3150** [comment]
西郷用メモ
IPressureCalculatorはparticlesを受け取ってpressureを返すことを保証するための規格を定めている．
それに合わせた実装がImplicitPressureCalculator
inteface.hppがすべてを規定している
virtualは仮想関数で，それがのちに実装されることを要求している→実装漏れを防げる
ImplicitPressureCalcularto : public IPressureCalculatorで継承している
IPressureCalculatorのうちどれを使うかは，simulation.cppで選択してからMPSクラスのコンストラクタに引き渡している．
