### ISSUE TITLE
Add calculation time to pr-comment

### ISSUE THREAD

**Issue by zukain5** [MPS-Basic/MPS-Basic#103]
CI で静水圧を計算したときのコメントに計算時間も加える。
計算時間が増えていないか/どれくらい増えたかをチェックできる。

**Comment by Quesys-tech** [comment]
こんなactionを見つけました
https://github.com/benchmark-action/github-action-benchmark

**Comment by zukain5** [comment]
@Quesys-tech こんなのあるんですね！今回はシンプルに console.log から実行時間を取ってくることにしました！
