### ISSUE TITLE
Change OpenMP requirements to 4.5

### ISSUE THREAD

**Issue by zukain5** [MPS-Basic/MPS-Basic#106]
Mac のデフォルトの clang だと OpenMP が使えない。
Homebrew 経由で入れた gcc だと OpenMP は使えるが、バージョンが 4.5 になる。
5.0 以上の機能を使っていなければ 4.5 にしたい。

**Comment by Quesys-tech** [comment]
OpenMP5.0以上ではじめてRange-based forの並列化に対応してます。
https://www.openmp.org/spec-html/5.1/openmpse84.html#x352-527000B.3

**Comment by zukain5** [comment]
うーんなるほど！！コンパイラを変えることで対応するしかないか・・・

**Comment by zukain5** [comment]
コンパイラを変えることで対応できたので、クローズ
