### ISSUE TITLE
High precision MPS

### ISSUE THREAD

**Issue by Quesys-tech** [MPS-Basic/MPS-Basic#12]
MPS法の高精度手法を入れる
- [x] E-MPS #45 
- [ ] #57
- [ ] #58
    - [ ] 速度の発散をとるやつ $\langle\nabla^2 P\rangle_i = -\frac{\rho}{\Delta t}\langle\nabla\cdot\mathbf{u}^\ast\rangle_i$
    - [ ] 複合型 $\langle\nabla^2 P\rangle_i = -\frac{\rho}{\Delta t}\left[(1-\gamma)\langle\nabla\cdot\mathbf{u}^\ast\rangle_i +\gamma\frac{n^\ast_i - n^0}{\Delta t}\right]$
    - [ ] #9 
- [x] 連立方程式の解法にCG法の類を使う
- [ ] #56
    - [ ] [Shibata et al.](https://doi.org/10.1007/s40571-015-0039-6)の仮想光源
    - [ ] [Sun et al.](http://dx.doi.org/10.1016/j.cma.2016.10.028)のモーメント行列の最小固有値の勾配

入れ方はオブジェクト指向を使って入れ、YAMLの設定ファイルで選択できるようにする

**Comment by zukain5** [comment]
@Quesys-tech 
これ issue 分割しませんか？
1 issue 1 PR のほうが開発しやすいかなと思っています
Projects とか使えばまとめることはできるかもしれないです

**Comment by Quesys-tech** [comment]
Projectsに引っ越します。

**Comment by Quesys-tech** [comment]
こちらにまとめました
https://github.com/orgs/MPS-Basic/projects/2/

**Comment by zukain5** [comment]
ありがとうございます！

**Comment by iori3150** [comment]
全てプロジェクトに移行したので閉じますー
