### ISSUE TITLE
Support particle data import from csv

### ISSUE THREAD

**Issue by zukain5** [MPS-Basic/MPS-Basic#124]
混相流の計算をできるようにするのためには、新たに fluidType をもたせる必要がある。
しかし、prof ファイルを変更したくない。
混相流の計算をするときには csv を入力データとするようにすれば、 prof を破壊せずにすむ。
そのためにまずは単相においても csv 入力をサポートする。

**Comment by Quesys-tech** [comment]
Profファイルをcsvに変換するスクリプトを書いて、既存のprofを変換してはどうでしょうか。

**Comment by zukain5** [comment]
Prof は粒子法界ではある程度一般的な気がするので、プログラムとしてprofを受け入れられるようにはしときたいなあと思っています
