### ISSUE TITLE
CI may have some problems

### ISSUE THREAD

**Issue by zukain5** [MPS-Basic/MPS-Basic#130]
main にマージしたときに走る Deploy の CI が動いていないようだった。
clang-tidy とかも最近気配を感じないので動いてないかもしれない。

**Comment by Quesys-tech** [comment]
調べたら以下の結果がわかりました。

- [actions/checkout](https://github.com/actions/checkout)が古くなっていました
- フォーマッタは動いているっぽいです 
- C++ tidy (linter)っぽいものは動いていなさそうです

コードの綺麗さを維持するためにtidyはしっかり規約を決めて動かしたほうがいいと思います。

**Comment by Quesys-tech** [comment]
clang-tidyで何を検知して修正させるか考えます
https://clang.llvm.org/extra/clang-tidy/

**Comment by Quesys-tech** [comment]
@zukain5 clang-tidyの項目は大量にあります。clang-tidyで何を検知するのかいいか議論するのは別issueを切ったほうがよいのではないでしょうか

**Comment by zukain5** [comment]
OKです


2024年5月27日(月) 21:21 QueueSys ***@***.***>:

**Comment by Quesys-tech** [comment]
#138 で議論しましょう
