### ISSUE TITLE
Give the Particle class the density of the fluid

### ISSUE THREAD

**Issue by zukain5** [MPS-Basic/MPS-Basic#131]
流体の密度は今は一定としているが、密度の違う複数の流体の計算を可能にするため、Particle に個別に持たせるようにする。

**Comment by Quesys-tech** [comment]
関連文献
- A. Shakibaeinia, Y.-C. Jin, MPS mesh-free particle method for multiphase flows, Computer Methods in Applied Mechanics and Engineering 229-232 (2012) 13–26. https://doi.org/10.1016/j.cma.2012.03.013.
- G. Duan, B. Chen, S. Koshizuka, H. Xiang, Stable multiphase moving particle semi-implicit method for incompressible interfacial flow, Computer Methods in Applied Mechanics and Engineering 318 (2017) 636–666. https://doi.org/10.1016/j.cma.2017.01.002.
