### ISSUE TITLE
Update Things Related to Generating input.prof

### ISSUE THREAD

**Issue by iori3150** [MPS-Basic/MPS-Basic#19]
- [x] Update CmakeLists.txt
- [x] Add instructions for making input.prof
- [x] Fix build errors for generate_dambreak.cpp
- [x] profとvtuをgitigunoreから除外

**Comment by iori3150** [comment]
@Quesys-tech 
現状generatorにあるCMakeListsって正常に動作しますか？
僕の環境だと上手くいかないです

**Comment by Quesys-tech** [comment]
そもそも単体でcmakeすることを想定していません。以下の理由によりプロジェクトのルートディレクトリのCMakeで一括管理するように書いています。
- CIで計算を回すときに一括管理のほうが楽だから
- Particlesクラスが関わっておりソルバーと別れていないから

ルートディレクトリでcmakeしてビルドしたらgeneratorもビルドされます。

**Comment by iori3150** [comment]
そうなんですね！
そしたらgenerator内のCMakeListsはもう不要ってことでしょうか？

**Comment by Quesys-tech** [comment]
まとめるとCMakeListsがわかりにくくなるので分割して書いています。

**Comment by iori3150** [comment]
あー，generator内のCMakeListsは上の階層のCMakeListsから呼ばれるだけってことですね！
納得しました
ありがとうございますー
