### ISSUE TITLE
Run simulation in CI

### ISSUE THREAD

**Issue by Quesys-tech** [MPS-Basic/MPS-Basic#42]
CIで静水圧平衡の計算を回して画像を比較できるようにしたい

**Comment by iori3150** [comment]
画像見れるようになったらめっちゃワクワクしますね！

**Comment by Quesys-tech** [comment]
Todo
- [ ] 静水圧平衝の計算を入れる
- [ ] CIでの可視化方法について調べる
- [ ] CIを書く

**Comment by Quesys-tech** [comment]
静水圧平衝のケースは 
Shibata, K., Masaie, I., Kondo, M. et al. Improved pressure calculation for the moving particle semi-implicit method. Comp. Part. Mech. 2, 91–108 (2015). https://doi.org/10.1007/s40571-015-0039-6
が比較に良さそう？

**Comment by Quesys-tech** [comment]
CIの回し方 https://discourse.paraview.org/t/run-paraview-in-github-actions/13101
