### ISSUE TITLE
Easily Changing Output Folder

### ISSUE THREAD

**Issue by iori3150** [MPS-Basic/MPS-Basic#44]
settings.ymlとscriptを両方変更しないといけないの面倒．

**Comment by iori3150** [comment]
@zukain5 @Quesys-tech 
setting.ymlの出力先情報は削除し，main関数の引数を増やして出力先情報をスクリプトから受け取る形にしようと思うのですがいかがでしょうか？
本当は逆にsettings.ymlのみに出力先情報を書く仕組みにしたかったんですが，フォルダの削除やログファイルの設定をスクリプトで行っている以上スクリプトに出力先情報を残しておく必要があるかなと思いました．

**Comment by zukain5** [comment]
悩ましいなあと思いましたが、自分としては当初やってた実行時刻ごとにフォルダを作る運用をやりたくて、それをスクリプトでやろうとすると main 関数の引数で出力先を受け取ってくれるとありがたいなーと思いました

というわけで賛成です！

**Comment by iori3150** [comment]
@Quesys-tech 
いかがでしょう？

**Comment by Quesys-tech** [comment]
承知しました。良いと思います。
