### ISSUE TITLE
Add Explicit Pressure Calculation onto Documentation

### ISSUE THREAD

**Issue by iori3150** [MPS-Basic/MPS-Basic#67]

**Comment by iori3150** [comment]
@zukain5 
インターフェースが必要なのってMPSクラスがpressureCalculator変数を持ってるから，その型として使えるものが必要ってことだと思うんだけど
圧力計算時に動的にpressureCalculator変数を定義するのじゃどうしてよくないの？
つまり，mps.cppのstepForward内で
```cpp
if(Implicit){
  Implicit pressureCalculator;
  pressures = pressureCalculator.run();

}else if(Explicit){
  Explicit pressureCalculator;
  pressures = pressureCalculator.run();
}
```
しちゃえばいいかと思ったんだけど

**Comment by iori3150** [comment]
- `Implicit`や`Explicit`クラスを`Interface`を継承する形で作成していれば，それらの実体をどこでどう呼び出すかに関係なく入出力形式を保証できる
- 結局どっかでif文で分けなきゃいけなくて，それをどこでやるかって話
- 最終的にライブラリ化するとすればそれはmain.cppでやるべき

**Comment by zukain5** [comment]
@iori3150 
考え直してシンプルにまとめられたんですが、今の実装は「圧力計算手法について、MPSクラスの外部から与えられる」のが明確な特徴って感じです。

**Comment by iori3150** [comment]
そうできることにはどんなメリットがあるのかな

**Comment by zukain5** [comment]
- MPSクラスを使う人が圧力計算手法を好きに決められる
- MPSクラスの内部の実装をいじらずに圧力計算手法を増やせる（ユーザーがオリジナルの手法を定義することもできる）
- ダミーとして「何を受け取っても 0 を返す圧力計算手法」みたいなのを作って MPS クラスに注入することで、MPSクラス自体のテストがしやすくなる（モックといいます）

って感じですかね

**Comment by zukain5** [comment]
簡単に言えば、「MPS クラスが圧力計算手法に依存しなくなる」のがメリットですね

**Comment by iori3150** [comment]
なるほど
MPSクラスの「責任」とか「目的」みたいなのは何になるの？

**Comment by iori3150** [comment]
MPSクラスは～～することのみが責任だから，圧力手法の選択はそこから外れるよね，ならすんなり納得できる

**Comment by zukain5** [comment]
MPSクラスの責任は、抽象的なんですが「粘性・外力による移動→圧力による移動」っていうアルゴリズム自体かな〜と考えています
EMPS はアルゴリズムが変わるので、別クラスに分けるべきかもと考えてる次第です

**Comment by iori3150** [comment]
アルゴリズム自体の実行であって，その各ステップの中身までは踏み込まないってことね
となると本当は重力計算とか粘性計算も他に任せるべきではあるってことか

**Comment by iori3150** [comment]
なんか誰になんの責任があるのか明確にして図とかにして記録しておきたいね

**Comment by zukain5** [comment]
そうですね、ただあんまり抽象化しすぎると冗長になるかなと思っているので、手法の差し替えが考えられないところは MPS クラスに埋め込んじゃう形でいいのかなと思っています

**Comment by iori3150** [comment]
- [ ] Interface: インターフェースを利用することでクラスの持つべき関数とその引数、戻り値を規定できる
- [ ] 実行時ポリモーフィズム: 基底クラスとポインタで実現
- [ ] 安全なポインタの使用
