### ISSUE TITLE
Particle Acceleration Not Iniialized After First Move

### ISSUE THREAD

**Issue by iori3150** [MPS-Basic/MPS-Basic#69]
本来は初期化されるべき流体粒子の加速度が初期化されていない
（えぐいバグですわ）
```cpp
void MPS::moveParticle() {
#pragma omp parallel for
    for (auto& p : particles) {
        if (p.type == ParticleType::Fluid) {
            p.velocity += p.acceleration * settings.dt;
            p.position += p.velocity * settings.dt;

        } else {
            p.acceleration.setZero();
        }
    }
}
```

**Comment by Quesys-tech** [comment]
初期化されてませんか？

**Comment by iori3150** [comment]
elseに入っちゃってるので流体粒子は初期化されないままなはずです

**Comment by iori3150** [comment]
実は以前静水圧が2倍になっちゃうことに気づいていて，そのブランチでは修正して静水圧が正しく出ることが確認できていたのですが，mainにマージしてなかったんです
そのブランチはもう古くなってしまったので新しく作り直しました

**Comment by iori3150** [comment]
> 初期化されてませんか？
> 
> https://github.com/MPS-Basic/MPS-Basic/blob/2bde21a6c3279367efb7e2c16026961aefb795c4/src/particle.hpp#L53

あ，すみません「初期化」っていう言葉の使い方が良くなかったかもです
リセットというかゼロに戻すというか，そういう意味での初期化です．

**Comment by Quesys-tech** [comment]
#59 で異常に高い圧力が出ていた理由がわかりました。ありがとうございます。
![pressure](https://github.com/MPS-Basic/MPS-Basic/assets/29653819/ffe92c08-e7a1-4b89-9d9d-df9acee31907)
