### ISSUE TITLE
How to Include Libraries in CMAKE

### ISSUE THREAD

**Issue by iori3150** [MPS-Basic/MPS-Basic#72]
現状
- Eigen: submodule
- yaml-cpp: FetchContent
- argparce: FetchContent
（GoogleTestはいろいろ書いてあって僕にはよく分からない）
統一した方がいいのでは？

**Comment by iori3150** [comment]
@Quesys-tech 
統一した方がいいのかなと思うのですが，どっちにするとかむしろ統一する必要がないとかあれば教えてください！

**Comment by Quesys-tech** [comment]
使うツールが増えるとわかりづらいので揃えたほうが良いと思います。
FetchContentはバージョンの固定ができる上に、自動でダウンロードしてくれるというgit submoduleにはない利点があるのでFetchContentが良いと思います。

**Comment by Quesys-tech** [comment]
https://github.com/MPS-Basic/MPS-Basic/pull/61#discussion_r1501820448

**Comment by iori3150** [comment]
Adress this after #61 is merged
