### ISSUE TITLE
Discuss the use of exception

### ISSUE THREAD

**Issue by Quesys-tech** [MPS-Basic/MPS-Basic#84]
コーディング規約で例外は使わないことになっているがargparseやyaml-cppは例外を送出するので対処せざるを得ない。
コーディング規約を変えて例外を限定的に認めたい。

C++の例外は
- ガベージコレクションがないためメモリーリークが起こりうる
- スタックトレースがないのでどこで何が起きたかわかりにくい

コーディング規約で
- MPS-Basicのコードでは例外を出さない
- 例外を受け取ったらその場で処理して、プログラムを終了させる
- どこで例外が起こったか明らかにする

としたい

**Comment by Quesys-tech** [comment]
@iori3150 @zukain5 いかがでしょうか？

**Comment by iori3150** [comment]
賛成です！
初心者もわかるようにドキュメントは詳しく書きたいですね．
例外ってどんなのとか，どんなのが良くないのか．

**Comment by zukain5** [comment]
いいと思います〜〜

**Comment by Quesys-tech** [comment]
@iori3150 
こんな感じでどうでしょうか
- 例外は通常の処理をすべて中断して呼び出し元にエラーを出す機能
- 例外の長所
  - 失敗を明確に伝えられる手段
- 例外の短所
  - すべてを中断するのでメモリーリークが起きやすい
  - 例外は伝播するので対応箇所が増える
- 参考文献
  - https://rinatz.github.io/cpp-book/ch10-01-exceptions/
  - https://google.github.io/styleguide/cppguide.html#Exceptions

**Comment by iori3150** [comment]
> @iori3150 
> 
> こんな感じでどうでしょうか
> 
> - 例外は通常の処理をすべて中断して呼び出し元にエラーを出す機能
> 
> - 例外の長所
> 
>   - 失敗を明確に伝えられる手段
> 
> - 例外の短所
> 
>   - すべてを中断するのでメモリーリークが起きやすい
> 
>   - 例外は伝播するので対応箇所が増える
> 
> - 参考文献
> 
>   - https://rinatz.github.io/cpp-book/ch10-01-exceptions/
> 
>   - https://google.github.io/styleguide/cppguide.html#Exceptions

整理されてわかりやすいですね！
良いと思います！
