### ISSUE TITLE
Introduce SPP (Space Potential Particle)

### ISSUE THREAD

**Issue by zukain5** [MPS-Basic/MPS-Basic#9]

**Comment by Quesys-tech** [comment]
It was merged to #12

**Comment by zukain5** [comment]
アルゴリズムは、collision までやったあと、

1. $n_i$ を計算する
1. $n_i < n_0$ なら SPP を neighbors に加える
1. 圧力ポアソン方程式をつくる
1. 解く

既存の「圧力ポアソン方程式をつくる」のところは `FluidState` に依存してるので、そのままつっこんでもうまくいかない。
「圧力ポアソン方程式メーカー」みたいなものがあればいいのかな？

**Comment by zukain5** [comment]
境界条件を考えなければ、圧力ポアソン方程式は以下の定数と変数がわかれば作れる

## 定数
- $n_0$
- $\lambda_0$
- $\rho_0$
- $d$
- $\delta t$

## 変数
- $n*$
- $w_ij$

これを作って、あとから境界条件を与えれば行ける説

**Comment by zukain5** [comment]
圧力ポアソンを作るときには、「row 側に含めるか」と「column 側に含めるか」の2つがあるけど、SPPのケースについては、「row 側には含めないけど、column 側には含める」という感じになる。
column 側は現状 `FluidState::Ignored` だけ弾いてるが、それがそのまま継続できそう。
row 側に含めないための処理は

1. row 側に含める粒子を明示的に指定する（`targetIds`）
2. row 側に含めない粒子を明示的に指定する（`excludedIds`）
3. `particle` を受け取って含めるかどうかを返す関数を指定する（`isTarget`）

の3つが考えられる。
計算量は

1. `targetIds` のループになるので O(N) （より気持ち少ない）
2. `particles` をループし `excludedIds` に含まれてたら弾くので O(NlogN)
3. `particles` をループし `istTarget` を適用するので O(N) * isTarget の計算量

1 か 3（どっちかといえば 1）がいい気がするなー

**Comment by Quesys-tech** [comment]
@zukain5 
#120 に合わせて閉じてしていいですか？

**Comment by zukain5** [comment]
OKです！とじます
